### ISSUE TITLE
Support for 'Background'

### ISSUE THREAD

**Issue by sriramvenkataram** [Vitalizzzer/cucumber-json-report-formatter#10]
Using background on cucumber scenarios seems to error out the formatter.

Am using the latest version (V0.0.9) of the formatter. 

Below is the feature,

![image](https://user-images.githubusercontent.com/91535830/185435074-3d406f5e-34c8-49cf-b619-6f72713128df.png)

Below is the Snapshot of the error,

![image](https://user-images.githubusercontent.com/91535830/185435301-f51b1e06-b128-46aa-83cc-17de6444f1f2.png)

**Comment by arithon55** [comment]
The Background is missing the Given keyword. It should be 
Background: Given I am on the Sportsbook Home page as a logged in user and my location verified

**Comment by sriramvenkataram** [comment]
Yes!! You're correct @arithon55 ! Sorry my bad! Thank you for pointing out!!
