### ISSUE TITLE
scenario Outline name is not captured properly in the json 

### ISSUE THREAD

**Issue by mrsenzy** [Vitalizzzer/cucumber-json-report-formatter#11]
First - Thanks much for this dependency. This really simplifies the exe cucumber json formatter file download and using it in repo. 

**Issue:** 
While running with scenario outline with examples. In cucumber-report.json the name field and steps.name field are not captured correctly, 

For e.g

Scenario Outline: <TC_ID> navigation from advanced search for <Role>
Given "<Role>" log into the application
When  user clicks Search from left menu
And   user navigate to Advance Search

Examples:
| TC_ID   | Role         |
| TC01.1  | System Admin |

Cucumber-report.json generated as below - Check the highlighted in bold (name and steps.name - both does not take the values from example table - it just display  as <TC_ID> and <Role>  

[
    {
        "comments": [],
        "description": "",
        "elements": [
            {
                "description": "",
                "id": "Advanced Search flow for System Admin;<TC_ID> Validate Customer 360 navigation from Advanced Search for <Role>",
                "keyword": "Scenario Outline",
                "line": 7,
                **"name": "<TC_ID> Validate Customer 360 navigation from Advanced Search for <Role>",**
                "steps": [
                    {
                        "keyword": "Given ",
                        "line": 8,
                        **"name": \<Role> log into the application",**
                        "result": {
                            "status": "passed",
                            "duration": 0
                        },
                        "embeddings": [],
                        "match": {
                            "location": "not available:0"
                        }
                    },

**Comment by vrymar** [comment]
Hi @mrsenzy! Could you please also provide **cucumber-messages.ndjson** file?

**Comment by mrsenzy** [comment]
[cucumber-messages.ndjson.txt](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/9698862/cucumber-messages.ndjson.txt)

Hi @Vitalizzzer  -  Please find the ndjson file attached in txt format. I ran couple of scenario outline feature in it. 

Many Thanks!

**Comment by vrymar** [comment]
Fixed by https://github.com/Vitalizzzer/cucumber-json-report-formatter/commit/6fa99253ce9c0000d068a80a16d8f0e9c66ffa77
Please, be aware of the following issue: https://github.com/Vitalizzzer/cucumber-json-report-formatter/issues/13
