### ISSUE TITLE
Unable to generate html report using cucumber-html-reporter

### ISSUE THREAD

**Issue by sagar-maheshwari** [Vitalizzzer/cucumber-json-report-formatter#16]
Is it just me or is anyone else facing an error with the latest version of cucumber-json-report-formatter while generating an HTML report using above mentioned packages?

Works fine till version 0.1.1 but breaks from 0.1.2.
I have attached the json file generated between v0.1.1 & 0.1.3. Doing a quick comparison between them, there seems to be an extra set of curly braces in the `elements` section which is failing the HTML generation.

Here are the json files for v0.1.1 & v0.1.3:
[cucumber-json-report-formatter-sample-zip.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/9983181/cucumber-json-report-formatter-sample-zip.zip)

Below is the error message coming out of cucumber-html-reporter:
![image](https://user-images.githubusercontent.com/58690196/201161487-1f11f9e0-de37-4673-b22d-b5596efcaf61.png)

**Comment by vrymar** [comment]
Hi @sagar-maheshwari ! Could you please provide the **cucumber-messages.ndjson** file?

**Comment by sagar-maheshwari** [comment]
Hi @Vitalizzzer , apologies I missed this message so couldn't send the ndjson file. Thank you so much for fixing the issue without it, the latest 0.1.4 version works well. Happy days!
