### ISSUE TITLE
Usage in cypress

### ISSUE THREAD

**Issue by oguzhantx** [Vitalizzzer/cucumber-json-report-formatter#3]
How do we exactly use this with cypress? does it go in the config.json file? Any suggestion is appreciated

**Comment by michaelsc93** [comment]
@oguzhantx Assuming you already have a cucumber preprocessor installed in your Cypress framework, this package turns the resulting cucumber-messages.ndjson file into a json file(see Usage in the README). 

The json file is usable with most reporting modules / you can upload results to test management softwares / etc

**Comment by oguzhantx** [comment]
Thanks, I was able to get it working for individual test file however, it does not work for multiple test files. It only have details of first test file in json and ignores the rest of the test files. Any idea why?

**Comment by arithon55** [comment]
When I follow your documentation it works for a simple scenario but fails for a multiple scenario feature file with

Start formatting file 'cucumber-messages.ndjson' into 'reports/cucumber-report.json'
An error was thrown in your plugins file while executing the handler for the after:run event.

The error we received was:

TypeError: Cannot read property 'steps' of undefined
    at C:\dev\bi---cypress-tests\node_modules\cucumber-json-report-formatter\lib\formatter.js:32:28
    at Array.forEach (<anonymous>)
    at Formatter.parseCucumberJson (C:\dev\bi---cypress-tests\node_modules\cucumber-json-report-formatter\lib\formatter.js:30:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Additionally the JSON file produced has output that is different from https://github.com/cucumber/json-formatter

1.  Status is uppercase whereas in JSON it should be lowercase. Multiple Cucumber HTML Reporter processes this as skipped because it doesn't recognise the status.
2.  Duration is always in seconds and is missing the milliseconds that is normally displayed in reports. Basically it is ignoring the nanos values in the ndjson file

I have attached a zip file with the ndjson file that caused the error and the json file produced by the cucumber json formatter that works with Multiple Cucumber HTML Reporter.

[formatter.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/9110232/formatter.zip)

**Comment by michaelsc93** [comment]
Hi @arithon55

For point 1, I created an issue on the multiple-cucumber-html-reporter here: https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/199

In the meantime my formatter code has a workaround to replace the capitals (it also uniquely timestamps test):
```
const Formatter = require('cucumber-json-report-formatter').Formatter;
const fs = require('fs');

const formatter = new Formatter();
const sourceFile = "./executions/unformatted-ndjson/cucumber-messages.ndjson";

let timeNow = getTime();
let outputFile = "./executions/formatted-json/execution_"+timeNow+"_results.json";

console.log("[Reporting] Formatting ndjson...");
parseThenReplaceCapitals();

function getTime()
{
    var d = new Date();
    var dateString =    (d.getDate() < 10 ? "0" + d.getDate() : d.getDate())
                      + "-"
                      + ((d.getMonth()+1) < 10 ? "0" + (d.getMonth()+1) : d.getMonth()+1)
                      + "-"
                      +  d.getFullYear()
                      + "-"
                      + (d.getHours() < 10 ? "0" + d.getHours() : d.getHours()) 
                      + (d.getMinutes() < 10 ? "0" + d.getMinutes() : d.getMinutes())
                      + (d.getSeconds() < 10? "0" + d.getSeconds() : d.getSeconds());
    return dateString;
}
async function parseThenReplaceCapitals()
{
    await formatter.parseCucumberJson(sourceFile, outputFile);

    try
    {
        var jsonFile = fs.readFileSync(__dirname + "\\executions\\formatted-json\\execution_"+timeNow+"_results.json");
        var json = JSON.parse(jsonFile);
        var jsonString = JSON.stringify(json);
            
        jsonString = replaceWord(jsonString, "FAILED", "failed");
        jsonString = replaceWord(jsonString, "PASSED", "passed");
        jsonString = replaceWord(jsonString, "SKIPPED", "skipped");
        jsonString = replaceWord(jsonString, "PENDING", "pending");
        
        console.log("Replaced test statuses to lowercase");

        fs.writeFileSync(outputFile, jsonString);
        console.log("Finalised file at "+outputFile);
    }
    catch(e)
    {
        console.log(e);
    }
}

function replaceWord(content, word, replacement)
{
    if(word == replacement)
        return;
    while(content.includes(word))
    {
        content = content.replace(word, replacement);
    }
    return content;
}
```
Feel free to borrow it

If you need nanoseconds I think you should raise a separate issue for point 2 with the test ndjson and expected json output

**Comment by michaelsc93** [comment]
@arithon55 Regarding the error, I have debugged it. It's because you have "background" within your gherkin. 

The "scenario" key doesn't exist and is instead called "background" on this child, hence "feature.scenario" is undefined (since it is instead "feature.background") and therefore it can't find those steps.

~~I'll create a bug fix that simply ignores "background" as I'm not sure how "background" is handled for formatting into the json file. It will at least let you have the json with the scenarios, the results and the attachments.~~

EDIT: I found a reference for how Background should be formatted in the json ( https://github.com/wswebcreation/multiple-cucumber-html-reporter/commit/0dc03721b2f8e886acac1edc687b4af102fc8159 ), I think I can implement this!
EDIT2: PR ready https://github.com/Vitalizzzer/cucumber-json-report-formatter/pull/4

**Comment by michaelsc93** [comment]
> Thanks, I was able to get it working for individual test file however, it does not work for multiple test files. It only have details of first test file in json and ignores the rest of the test files. Any idea why?

Assuming you are using multiple-cucumber-html-reporter, make sure your json files are uniquely named

**Comment by oguzhantx** [comment]
> > Thanks, I was able to get it working for individual test file however, it does not work for multiple test files. It only have details of first test file in json and ignores the rest of the test files. Any idea why?
> 
> Assuming you are using multiple-cucumber-html-reporter, make sure your json files are uniquely named

well, formatter creates the json file by reading from ./cucumber-messages.ndjson file as part of this formatter implementation. it is not like I got to decide on that part anyways. are you suggesting outputFile configuration change in report-formatter.js file would do that? 

const outputFile =
    'cypress/reports/cucumber-json/formatted-cucumber-report.json';

**Comment by michaelsc93** [comment]
> > > Thanks, I was able to get it working for individual test file however, it does not work for multiple test files. It only have details of first test file in json and ignores the rest of the test files. Any idea why?
> > 
> > 
> > Assuming you are using multiple-cucumber-html-reporter, make sure your json files are uniquely named
> 
> well, formatter creates the json file by reading from ./cucumber-messages.ndjson file as part of this formatter implementation. it is not like I got to decide on that part anyways. are you suggesting outputFile configuration change in report-formatter.js file would do that?
> 
> const outputFile = 'cypress/reports/cucumber-json/formatted-cucumber-report.json';

Yeah exactly, if you give it a timestamp or guid then all the json files will be unique & will appear on a generated multiple-cucumber-html-report. EG
```
const outputFile = 'cypress/reports/cucumber-json/formatted-cucumber-report'+new Date()+'.json';
```
Or my code from above does it with a nicer date format

**Comment by oguzhantx** [comment]
> > > > Thanks, I was able to get it working for individual test file however, it does not work for multiple test files. It only have details of first test file in json and ignores the rest of the test files. Any idea why?
> > > 
> > > 
> > > Assuming you are using multiple-cucumber-html-reporter, make sure your json files are uniquely named
> > 
> > 
> > well, formatter creates the json file by reading from ./cucumber-messages.ndjson file as part of this formatter implementation. it is not like I got to decide on that part anyways. are you suggesting outputFile configuration change in report-formatter.js file would do that?
> > const outputFile = 'cypress/reports/cucumber-json/formatted-cucumber-report.json';
> 
> Yeah exactly, if you give it a timestamp or guid then all the json files will be unique & will appear on a generated multiple-cucumber-html-report. EG
> 
> ```
> const outputFile = 'cypress/reports/cucumber-json/formatted-cucumber-report'+new Date()+'.json';
> ```
> 
> Or my code from above does it with a nicer date format



> > > > Thanks, I was able to get it working for individual test file however, it does not work for multiple test files. It only have details of first test file in json and ignores the rest of the test files. Any idea why?
> > > 
> > > 
> > > Assuming you are using multiple-cucumber-html-reporter, make sure your json files are uniquely named
> > 
> > 
> > well, formatter creates the json file by reading from ./cucumber-messages.ndjson file as part of this formatter implementation. it is not like I got to decide on that part anyways. are you suggesting outputFile configuration change in report-formatter.js file would do that?
> > const outputFile = 'cypress/reports/cucumber-json/formatted-cucumber-report.json';
> 
> Yeah exactly, if you give it a timestamp or guid then all the json files will be unique & will appear on a generated multiple-cucumber-html-report. EG
> 
> ```
> const outputFile = 'cypress/reports/cucumber-json/formatted-cucumber-report'+new Date()+'.json';
> ```
> 
> Or my code from above does it with a nicer date format

Issue is not about name convention or same name being overwritten but how the .ndjson file is being translated to create a json file. when i run a npm command it runs 10 different test files and i can see all those test details in the .ndjson however when it comes to creating the formatted json file by reading the ndjson, that final formatted json file only has one test details.
check these out. 
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/94402055/179059994-e12faa47-24fb-4ca2-a42b-7477ec525d15.png">

<img width="1670" alt="Screen Shot 2022-07-14 at 1 46 29 PM" src="https://user-images.githubusercontent.com/94402055/179060066-b64836c8-c8fa-42e6-8e8d-946f0b29193b.png">

**Comment by arithon55** [comment]
Thanks for the prompt and thorough response. My 2 points (for status casing and duration) were pointing out differences in your JSON and that produced by the Cucumber project standalone JSON formatter (https://github.com/cucumber/json-formatter). The JSON from Cucumber project works with the Multiple Cucumber HTML Reporter and other reporters. However, being standalone makes it difficult to incorporate in our Cypress test framework. A NPM package like yours is what I am looking for and the effort to produce it is much appreciated.

**Comment by vrymar** [comment]
@michaelsc93 implemented "Added support for 'Background' gherkin syntax". Thanks a lot! It is already in the latest version 0.0.8 https://www.npmjs.com/package/cucumber-json-report-formatter

**Comment by michaelsc93** [comment]
@oguzhantx can you supply the ndjson file so I can investigate why some are missed?

**Comment by arithon55** [comment]
https://github.com/Vitalizzzer/cucumber-json-report-formatter/issues/3#issuecomment-1184183340 has a zip file with the ndjson file and the JSON file produced from it by using the Cucumber Standalone JSON formatter.

**Comment by sriramvenkataram** [comment]
Hello,
Been trying to use the latest version of the package with [cucumber-html-reporter](https://www.npmjs.com/package/cucumber-html-reporter). The output report seems to show the scenarios as skipped though they have been executed. The same seems to appear fine while using [cucumber-json-formatter-standalone](https://github.com/cucumber/json-formatter)https://github.com/cucumber/json-formatter). 

Using the standalone in the test frameworks seem troublesome while an NPM package as yours makes it easier. Would be great if this can be looked into!! 


![Screenshot 2022-07-18 at 15 54 50](https://user-images.githubusercontent.com/91535830/179548537-151af95f-739e-4dbf-9fd7-a3f3556900f7.png)

Also attaching the 'cucumber-messages.ndjson' file.
[cucumber-messages.ndjson.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/9133314/cucumber-messages.ndjson.zip)

**Comment by michaelsc93** [comment]
Wow hi @sriramvenkataram small world! :) I used to work with you

See here for the issue of "Skipped", it is more a reporting issue with multiple reporter: https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/199

As a workaround you can replace uppercase status (e.g. "PASSED") with lowercase within the json (see my code above as an example)

**Comment by sriramvenkataram** [comment]
> wswebcreation/multiple-cucumber-html-reporter#199

Hi @michaelsc93 !!! Small world indeed, really happy to see you here!! :-) 

Just to clarify, am not using multiple-cucumber-html reporter. Using the cucumber-html-reporter V5.5 https://www.npmjs.com/package/cucumber-html-reporter 

Considering the output format of the package is different from what most of the report generators expect (also different from the output of cucumber-json-formatter-standalone). Would it be worth considering fixing it within the package than a separate script?

**Comment by michaelsc93** [comment]
@sriramvenkataram Yes if it is in several reporting I agree it should be changed to fit the previous standard

I created a PR to address both the status issue and the missing features which @oguzhantx mentioned

https://github.com/Vitalizzzer/cucumber-json-report-formatter/pull/5 @Vitalizzzer please have a look 👍

**Comment by vrymar** [comment]
@michaelsc93 @sriramvenkataram @oguzhantx approved and published with version 0.0.9. Thanks!

**Comment by vrymar** [comment]
Closing this issue. If another one appears, please open it.

**Comment by JomyGeo** [comment]
@Vitalizzzer 
 I could not generate the report(CUCUMBER-REPORT.JSON) if I am adding the below code in my index.js. 

In my case, I want to show additional details in the custom data section of the report which I can get from the cypress result JSON file. Please do let me know how to handle it

Note: Report is working fine if I don't use the below code in index.js and  CUCUMBER-REPORT.JSON generated properly 


 on('after:run', (results) => {
    if (results) {
      fs.mkdirSync("cypress/.run", { recursive: true });
      fs.writeFile("cypress/.run/results.json", JSON.stringify(results));
    }
  })

**Comment by sriramvenkataram** [comment]
Hi ,

The following little write-up might be useful for anyone looking forward to use this package with cypress-cucumber combination.

https://medium.com/@sriram.venkataram/cypress-cucumber-test-framework-with-html-reporting-be19592b1361

**Comment by arithon55** [comment]
The above works but all steps in the report give a duration of <1ms see https://github.com/Vitalizzzer/cucumber-json-report-formatter/issues/9
