### ISSUE TITLE
Bug: Scenario Outline / Examples data not being captured in JSON

### ISSUE THREAD

**Issue by michaelsc93** [Vitalizzzer/cucumber-json-report-formatter#6]
This is an issue where if there is following Gherkin:
```
    @smokeTest
    Scenario Outline: Verify country name mentioned under regions "<countryName>"
        Given User verifies country name on country selection modal "<countryName>"

        Examples:
            | countryName         |
            | Australia           |
            | New Zealand         |
```

Then only the first execution is captured into the JSON. The Examples data is not captured either & the Scenario will be defined as a single execution of "Given User verifies country name on country selection modal <countryName>". 

The worrying part of this not being captured is that if the 2nd (New Zealand) execution fails, this is not captured in the JSON / subsequent reporting.

I need some assistance before working on fixing this, as I am not sure how the Cucumber JSON output should be formatted to include Examples data where users are utilising this Scenario Outline functionality. 

If someone can provide a NDJSON or Gherkin, as well as an expected JSON output I would be happy to try to fix it. For now I am not sure how the JSON should be created

**Comment by vrymar** [comment]
@michaelsc93 check the attached report file for the following scenario:

Feature:ah.nl
  Scenario Outline: Scenario Outline name: visting the frontpage
    Given I need to visit "< site >"
    When I click on the menu bar
    Then I should enter random name in search bar

    Examples:
    |site|
    |https://www.ah.nl/|
    |https://www.aholddelhaize.com/|
[cucumber-messages.zip](https://github.com/Vitalizzzer/cucumber-json-report-formatter/files/9142066/cucumber-messages.zip)

**Comment by michaelsc93** [comment]
@Vitalizzzer so in this case I see there is 1 execution in the formatted JSON where we should expect 2 (1 per example data) - but I'm not sure how this should be created in the JSON.

should we check for Outline keyword and then generate multiple scenarios? & then replace <data> with the relevant run? It seems complex

**Comment by vitaliirymar** [comment]
@michaelsc93 you can leave it for me. But I can't plan it for now. As I have the possibility, I'll check the workflows and create a fix.

**Comment by michaelsc93** [comment]
@vitaliirymar I gave it a try, my attempt is here: https://github.com/Vitalizzzer/cucumber-json-report-formatter/pull/8 appears to be working

@Vitalizzzer fyi

**Comment by oguzhantx** [comment]
When can we get this working? Any timeline to merge @michaelsc93's fix ?

**Comment by vrymar** [comment]
@oguzhantx , checked @michaelsc93 's pull request. Publishing the formatted report to Zephyr Scale failed. Commented in the pull request.

**Comment by burakkaygusuz** [comment]
@Vitalizzzer Hi, is there any progress?

**Comment by vrymar** [comment]
Hi @burakkaygusuz ! Currently I'm fully occupied. Will check the issue when it is possible. You are welcome to contribute into the project!

**Comment by vrymar** [comment]
@michaelsc93 , @oguzhantx , @burakkaygusuz for now the fix/pull request provided by @michaelsc93 is approved. https://github.com/Vitalizzzer/cucumber-json-report-formatter/pull/8
It is already in the latest version 0.1.0 here: https://www.npmjs.com/package/cucumber-json-report-formatter
Please, pay attention to the following issue: https://github.com/Vitalizzzer/cucumber-json-report-formatter/pull/8#issuecomment-1217651861
